---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/BMP_Table1/BMP_Table1.xlsx
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/102716/articles/173986/master/file/figures/BMP_Table1/BMP_Table1.xlsx"
    folder_url: "/users/102716/articles/173986/master/folder/figures/BMP_Table1"
    treatFirstLineAsHeader: true
    fontSize: footnotesize
